# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutUs.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutPage(object):
    def setupUi(self, AboutPage):
        AboutPage.setObjectName("AboutPage")
        AboutPage.resize(436, 596)
        AboutPage.setMinimumSize(QtCore.QSize(436, 527))
        AboutPage.setMaximumSize(QtCore.QSize(504, 596))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutPage.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AboutPage)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.imageView = QtWidgets.QLabel(self.centralwidget)
        self.imageView.setMinimumSize(QtCore.QSize(100, 100))
        self.imageView.setText("")
        self.imageView.setPixmap(QtGui.QPixmap("GUI/favicon.ico"))
        self.imageView.setAlignment(QtCore.Qt.AlignCenter)
        self.imageView.setObjectName("imageView")
        self.verticalLayout.addWidget(self.imageView)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(400, 0))
        self.label_2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(55, 115, 171);")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(False)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("color: rgb(42, 91, 144);")
        self.label_5.setIndent(12)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("color: rgb(42, 91, 144);")
        self.label_6.setIndent(12)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("color: rgb(42, 91, 144);")
        self.label_7.setIndent(12)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("color: rgb(42, 91, 144);")
        self.label_8.setIndent(12)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("color: rgb(42, 91, 144);")
        self.label_9.setIndent(12)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setStyleSheet("color: rgb(42, 91, 144);")
        self.label_10.setIndent(12)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.visitUsButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.visitUsButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.visitUsButton.setObjectName("visitUsButton")
        self.horizontalLayout_2.addWidget(self.visitUsButton)
        self.SourceCodeButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.SourceCodeButton.setObjectName("SourceCodeButton")
        self.horizontalLayout_2.addWidget(self.SourceCodeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        AboutPage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AboutPage)
        self.statusbar.setObjectName("statusbar")
        AboutPage.setStatusBar(self.statusbar)

        self.retranslateUi(AboutPage)
        QtCore.QMetaObject.connectSlotsByName(AboutPage)

    def retranslateUi(self, AboutPage):
        _translate = QtCore.QCoreApplication.translate
        AboutPage.setWindowTitle(_translate("AboutPage", "About Us"))
        self.label.setText(_translate("AboutPage", "About Us"))
        self.label_2.setText(_translate("AboutPage", "This battery of logic design related solvers & converters was implemented by a undergraduate students\' group\n"
"of the University of Thessaly Computer Science Dept, as a by-product of an unofficial \n"
"summer school aiming at the development and enrichment of their Python programming skills.\n"
"The creation of the application at hand aims to help fellow students to learn and understand basic\n"
"logic design concepts while having a versatile helper at their disposal."))
        self.label_4.setText(_translate("AboutPage", "Developed by: "))
        self.label_5.setText(_translate("AboutPage", "• Aris Karabelas Timotijevic - Meremetis"))
        self.label_6.setText(_translate("AboutPage", "• George Kranas - The color-blind eagle "))
        self.label_7.setText(_translate("AboutPage", "• Gefsi Euaggelidou - The only girl"))
        self.label_8.setText(_translate("AboutPage", "• Daniel Trontsios - Sweet Like Tronky"))
        self.label_9.setText(_translate("AboutPage", "• Sotiris Sapakos - GUI Master"))
        self.label_10.setText(_translate("AboutPage", "• Vasilis Dimitriadis - Slave Master"))
        self.visitUsButton.setText(_translate("AboutPage", "Visit us"))
        self.SourceCodeButton.setText(_translate("AboutPage", "Source Code"))

