# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LDSMenu.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
#from LDS import imageResources

class Ui_LDS(object):
    def setupUi(self, LDS):
        LDS.setObjectName("LDS")
        LDS.resize(548, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LDS.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LDS)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(55, 115, 171);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.arithmetic_expressions = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.arithmetic_expressions.setObjectName("arithmetic_expressions")
        self.verticalLayout.addWidget(self.arithmetic_expressions)
        self.base_converter = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.base_converter.setObjectName("base_converter")
        self.verticalLayout.addWidget(self.base_converter)
        self.complement_solver = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.complement_solver.setObjectName("complement_solver")
        self.verticalLayout.addWidget(self.complement_solver)
        self.calculator = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.calculator.setObjectName("calculator")
        self.verticalLayout.addWidget(self.calculator)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(55, 115, 171);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.kmap_solver = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.kmap_solver.setObjectName("kmap_solver")
        self.verticalLayout.addWidget(self.kmap_solver)
        self.bdd = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.bdd.setObjectName("bdd")
        self.verticalLayout.addWidget(self.bdd)
        self.Quine_McCluskey = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.Quine_McCluskey.setObjectName("Quine_McCluskey")
        self.verticalLayout.addWidget(self.Quine_McCluskey)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(55, 115, 171);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ExitButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout_2.addWidget(self.ExitButton)
        self.AboutUsButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.AboutUsButton.setObjectName("AboutUsButton")
        self.horizontalLayout_2.addWidget(self.AboutUsButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        LDS.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LDS)
        self.statusbar.setObjectName("statusbar")
        LDS.setStatusBar(self.statusbar)

        self.retranslateUi(LDS)
        QtCore.QMetaObject.connectSlotsByName(LDS)

    def retranslateUi(self, LDS):
        _translate = QtCore.QCoreApplication.translate
        LDS.setWindowTitle(_translate("LDS", "Logic Design Solver"))
        self.label.setText(_translate("LDS", "Menu"))
        self.label_2.setText(_translate("LDS", "Please choose a solver "))
        self.label_3.setText(_translate("LDS", "Basic solvers"))
        self.arithmetic_expressions.setText(_translate("LDS", "Arithmetic Expression"))
        self.base_converter.setText(_translate("LDS", "Base Converter"))
        self.complement_solver.setText(_translate("LDS", "Complement Finder"))
        self.calculator.setText(_translate("LDS", "Calculator"))
        self.label_4.setText(_translate("LDS", "Advanced Solvers"))
        self.kmap_solver.setText(_translate("LDS", "Karnaugh Map Solver"))
        self.bdd.setText(_translate("LDS", "BDD (Binary Decision Diagram)"))
        self.Quine_McCluskey.setText(_translate("LDS", "Quine - McCluskey"))
        self.label_5.setText(_translate("LDS", "Other"))
        self.ExitButton.setText(_translate("LDS", "Exit"))
        self.AboutUsButton.setText(_translate("LDS", "About Us"))

