# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArithmeticExpression.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArithmeticExpression(object):
    def setupUi(self, ArithmeticExpression):
        ArithmeticExpression.setObjectName("ArithmeticExpression")
        ArithmeticExpression.resize(630, 337)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ArithmeticExpression.setWindowIcon(icon)
        ArithmeticExpression.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ArithmeticExpression)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(70, 141, 212);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.resultText = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.resultText.setFont(font)
        self.resultText.setStyleSheet("color: rgb(39, 80, 120);")
        self.resultText.setObjectName("resultText")
        self.verticalLayout.addWidget(self.resultText)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(60, 121, 182);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(60, 121, 182);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.numberText = QtWidgets.QTextEdit(self.centralwidget)
        self.numberText.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setItalic(False)
        self.numberText.setFont(font)
        self.numberText.setStyleSheet("color: rgb(38, 78, 117);")
        self.numberText.setObjectName("numberText")
        self.horizontalLayout_3.addWidget(self.numberText)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(60, 121, 182);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.baseFromSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.baseFromSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.baseFromSpinBox.setFont(font)
        self.baseFromSpinBox.setStyleSheet("color: rgb(43, 88, 132);")
        self.baseFromSpinBox.setMinimum(2)
        self.baseFromSpinBox.setMaximum(36)
        self.baseFromSpinBox.setObjectName("baseFromSpinBox")
        self.horizontalLayout_4.addWidget(self.baseFromSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(60, 121, 182);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.baseToSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.baseToSpinBox.setMinimumSize(QtCore.QSize(20, 0))
        self.baseToSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.baseToSpinBox.setFont(font)
        self.baseToSpinBox.setStyleSheet("color: rgb(43, 88, 132);")
        self.baseToSpinBox.setMinimum(2)
        self.baseToSpinBox.setMaximum(36)
        self.baseToSpinBox.setObjectName("baseToSpinBox")
        self.horizontalLayout_5.addWidget(self.baseToSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.findExpressionButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.findExpressionButton.setStyleSheet("")
        self.findExpressionButton.setObjectName("findExpressionButton")
        self.verticalLayout_2.addWidget(self.findExpressionButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        ArithmeticExpression.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ArithmeticExpression)
        self.statusbar.setObjectName("statusbar")
        ArithmeticExpression.setStatusBar(self.statusbar)
        self.actionInputs = QtWidgets.QAction(ArithmeticExpression)
        self.actionInputs.setObjectName("actionInputs")
        self.actionParametres = QtWidgets.QAction(ArithmeticExpression)
        self.actionParametres.setObjectName("actionParametres")
        self.actionSolution = QtWidgets.QAction(ArithmeticExpression)
        self.actionSolution.setObjectName("actionSolution")

        self.retranslateUi(ArithmeticExpression)
        QtCore.QMetaObject.connectSlotsByName(ArithmeticExpression)

    def retranslateUi(self, ArithmeticExpression):
        _translate = QtCore.QCoreApplication.translate
        ArithmeticExpression.setWindowTitle(_translate("ArithmeticExpression", "Arithmetic Expression"))
        self.label.setText(_translate("ArithmeticExpression", "Result"))
        self.label_2.setText(_translate("ArithmeticExpression", "Input"))
        self.label_3.setText(_translate("ArithmeticExpression", "Number:"))
        self.label_4.setText(_translate("ArithmeticExpression", "Base From:"))
        self.label_5.setText(_translate("ArithmeticExpression", "Base To:"))
        self.findExpressionButton.setText(_translate("ArithmeticExpression", "Find Expression"))
        self.actionInputs.setText(_translate("ArithmeticExpression", "Inputs"))
        self.actionParametres.setText(_translate("ArithmeticExpression", "Parameters"))
        self.actionSolution.setText(_translate("ArithmeticExpression", "Solution"))
