# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KMapSolvers.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KMapSolvers(object):
    def setupUi(self, KMapSolvers):
        KMapSolvers.setObjectName("KMapSolvers")
        KMapSolvers.resize(591, 596)
        KMapSolvers.setMinimumSize(QtCore.QSize(494, 473))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KMapSolvers.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(KMapSolvers)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 4, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 2, 3, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 2, 4, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 3, 5, 1, 1)
        self.but_2__1_0 = QtWidgets.QPushButton(self.tab)
        self.but_2__1_0.setMinimumSize(QtCore.QSize(0, 40))
        self.but_2__1_0.setMaximumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_2__1_0.setFont(font)
        self.but_2__1_0.setObjectName("but_2__1_0")
        self.gridLayout.addWidget(self.but_2__1_0, 4, 3, 1, 1)
        self.but_2__0_1 = QtWidgets.QPushButton(self.tab)
        self.but_2__0_1.setMinimumSize(QtCore.QSize(0, 40))
        self.but_2__0_1.setMaximumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_2__0_1.setFont(font)
        self.but_2__0_1.setObjectName("but_2__0_1")
        self.gridLayout.addWidget(self.but_2__0_1, 3, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 3, 1, 1)
        self.but_2__0_0 = QtWidgets.QPushButton(self.tab)
        self.but_2__0_0.setMinimumSize(QtCore.QSize(40, 40))
        self.but_2__0_0.setMaximumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_2__0_0.setFont(font)
        self.but_2__0_0.setObjectName("but_2__0_0")
        self.gridLayout.addWidget(self.but_2__0_0, 3, 3, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 4, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setStyleSheet("color: rgb(70, 141, 212);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.but_2__1_1 = QtWidgets.QPushButton(self.tab)
        self.but_2__1_1.setMinimumSize(QtCore.QSize(40, 40))
        self.but_2__1_1.setMaximumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_2__1_1.setFont(font)
        self.but_2__1_1.setObjectName("but_2__1_1")
        self.gridLayout.addWidget(self.but_2__1_1, 4, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 4, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 1, 1, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.tab)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 2, 1, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 3, 1, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.tab)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 4, 1, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.tab)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 1, 3, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.tab)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_2.addWidget(self.line_15, 2, 3, 1, 1)
        self.line_46 = QtWidgets.QFrame(self.tab)
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.gridLayout_2.addWidget(self.line_46, 4, 3, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.tab)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_2.addWidget(self.line_16, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        self.KMap_2__0_1 = QtWidgets.QPushButton(self.tab)
        self.KMap_2__0_1.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_2__0_1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_2__0_1.setFont(font)
        self.KMap_2__0_1.setObjectName("KMap_2__0_1")
        self.gridLayout_2.addWidget(self.KMap_2__0_1, 2, 2, 1, 1)
        self.KMap_2__0_0 = QtWidgets.QPushButton(self.tab)
        self.KMap_2__0_0.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_2__0_0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_2__0_0.setFont(font)
        self.KMap_2__0_0.setObjectName("KMap_2__0_0")
        self.gridLayout_2.addWidget(self.KMap_2__0_0, 1, 2, 1, 1)
        self.KMap_2__1_0 = QtWidgets.QPushButton(self.tab)
        self.KMap_2__1_0.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_2__1_0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_2__1_0.setFont(font)
        self.KMap_2__1_0.setObjectName("KMap_2__1_0")
        self.gridLayout_2.addWidget(self.KMap_2__1_0, 3, 2, 1, 1)
        self.KMap_2__1_1 = QtWidgets.QPushButton(self.tab)
        self.KMap_2__1_1.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_2__1_1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_2__1_1.setFont(font)
        self.KMap_2__1_1.setObjectName("KMap_2__1_1")
        self.gridLayout_2.addWidget(self.KMap_2__1_1, 4, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 5, 2, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.result2VarsEditText = QtWidgets.QTextEdit(self.tab)
        self.result2VarsEditText.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.result2VarsEditText.setFont(font)
        self.result2VarsEditText.setStyleSheet("color: rgb(43, 88, 132);")
        self.result2VarsEditText.setObjectName("result2VarsEditText")
        self.horizontalLayout_2.addWidget(self.result2VarsEditText)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.buttonSolve2varsMap = QtWidgets.QCommandLinkButton(self.tab)
        self.buttonSolve2varsMap.setObjectName("buttonSolve2varsMap")
        self.verticalLayout_2.addWidget(self.buttonSolve2varsMap)
        self.clear2 = QtWidgets.QCommandLinkButton(self.tab)
        self.clear2.setObjectName("clear2")
        self.verticalLayout_2.addWidget(self.clear2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_22 = QtWidgets.QFrame(self.tab_2)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_3.addWidget(self.line_22, 2, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 6, 1, 1)
        self.but_3__0_0 = QtWidgets.QPushButton(self.tab_2)
        self.but_3__0_0.setMinimumSize(QtCore.QSize(40, 40))
        self.but_3__0_0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.but_3__0_0.setFont(font)
        self.but_3__0_0.setObjectName("but_3__0_0")
        self.gridLayout_3.addWidget(self.but_3__0_0, 3, 3, 1, 1)
        self.but_3__1_3 = QtWidgets.QPushButton(self.tab_2)
        self.but_3__1_3.setMinimumSize(QtCore.QSize(40, 40))
        self.but_3__1_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.but_3__1_3.setFont(font)
        self.but_3__1_3.setObjectName("but_3__1_3")
        self.gridLayout_3.addWidget(self.but_3__1_3, 4, 6, 1, 1)
        self.but_3__0_1 = QtWidgets.QPushButton(self.tab_2)
        self.but_3__0_1.setMinimumSize(QtCore.QSize(40, 40))
        self.but_3__0_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.but_3__0_1.setFont(font)
        self.but_3__0_1.setObjectName("but_3__0_1")
        self.gridLayout_3.addWidget(self.but_3__0_1, 3, 4, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.tab_2)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_3.addWidget(self.line_17, 4, 2, 1, 1)
        self.but_3__1_0 = QtWidgets.QPushButton(self.tab_2)
        self.but_3__1_0.setMinimumSize(QtCore.QSize(40, 40))
        self.but_3__1_0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.but_3__1_0.setFont(font)
        self.but_3__1_0.setObjectName("but_3__1_0")
        self.gridLayout_3.addWidget(self.but_3__1_0, 4, 3, 1, 1)
        self.but_3__0_3 = QtWidgets.QPushButton(self.tab_2)
        self.but_3__0_3.setMinimumSize(QtCore.QSize(40, 40))
        self.but_3__0_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.but_3__0_3.setFont(font)
        self.but_3__0_3.setObjectName("but_3__0_3")
        self.gridLayout_3.addWidget(self.but_3__0_3, 3, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 5, 1, 1)
        self.but_3__0_2 = QtWidgets.QPushButton(self.tab_2)
        self.but_3__0_2.setMinimumSize(QtCore.QSize(40, 40))
        self.but_3__0_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.but_3__0_2.setFont(font)
        self.but_3__0_2.setObjectName("but_3__0_2")
        self.gridLayout_3.addWidget(self.but_3__0_2, 3, 5, 1, 1)
        self.but_3__1_1 = QtWidgets.QPushButton(self.tab_2)
        self.but_3__1_1.setMinimumSize(QtCore.QSize(40, 40))
        self.but_3__1_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.but_3__1_1.setFont(font)
        self.but_3__1_1.setObjectName("but_3__1_1")
        self.gridLayout_3.addWidget(self.but_3__1_1, 4, 4, 1, 1)
        self.but_3__1_2 = QtWidgets.QPushButton(self.tab_2)
        self.but_3__1_2.setMinimumSize(QtCore.QSize(40, 40))
        self.but_3__1_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.but_3__1_2.setFont(font)
        self.but_3__1_2.setObjectName("but_3__1_2")
        self.gridLayout_3.addWidget(self.but_3__1_2, 4, 5, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.tab_2)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_3.addWidget(self.line_18, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 3, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.tab_2)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout_3.addWidget(self.line_27, 5, 5, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.tab_2)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout_3.addWidget(self.line_25, 5, 3, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.tab_2)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout_3.addWidget(self.line_26, 5, 4, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.tab_2)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_3.addWidget(self.line_21, 2, 5, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.tab_2)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_3.addWidget(self.line_19, 2, 3, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.tab_2)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_3.addWidget(self.line_20, 2, 4, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.tab_2)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_3.addWidget(self.line_23, 3, 7, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.tab_2)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout_3.addWidget(self.line_24, 4, 7, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.tab_2)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout_3.addWidget(self.line_28, 5, 6, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 6, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 0, 5, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 3, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem13, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 5, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 8, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 7, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 3, 0, 1, 1)
        self.KMap_3__0_3 = QtWidgets.QPushButton(self.tab_2)
        self.KMap_3__0_3.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_3__0_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_3__0_3.setFont(font)
        self.KMap_3__0_3.setObjectName("KMap_3__0_3")
        self.gridLayout_5.addWidget(self.KMap_3__0_3, 3, 2, 1, 1)
        self.KMap_3__0_1 = QtWidgets.QPushButton(self.tab_2)
        self.KMap_3__0_1.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_3__0_1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_3__0_1.setFont(font)
        self.KMap_3__0_1.setObjectName("KMap_3__0_1")
        self.gridLayout_5.addWidget(self.KMap_3__0_1, 2, 2, 1, 1)
        self.KMap_3__0_2 = QtWidgets.QPushButton(self.tab_2)
        self.KMap_3__0_2.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_3__0_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_3__0_2.setFont(font)
        self.KMap_3__0_2.setObjectName("KMap_3__0_2")
        self.gridLayout_5.addWidget(self.KMap_3__0_2, 4, 2, 1, 1)
        self.KMap_3__1_0 = QtWidgets.QPushButton(self.tab_2)
        self.KMap_3__1_0.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_3__1_0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_3__1_0.setFont(font)
        self.KMap_3__1_0.setObjectName("KMap_3__1_0")
        self.gridLayout_5.addWidget(self.KMap_3__1_0, 5, 2, 1, 1)
        self.KMap_3__1_1 = QtWidgets.QPushButton(self.tab_2)
        self.KMap_3__1_1.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_3__1_1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_3__1_1.setFont(font)
        self.KMap_3__1_1.setObjectName("KMap_3__1_1")
        self.gridLayout_5.addWidget(self.KMap_3__1_1, 6, 2, 1, 1)
        self.KMap_3__1_2 = QtWidgets.QPushButton(self.tab_2)
        self.KMap_3__1_2.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_3__1_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_3__1_2.setFont(font)
        self.KMap_3__1_2.setObjectName("KMap_3__1_2")
        self.gridLayout_5.addWidget(self.KMap_3__1_2, 8, 2, 1, 1)
        self.KMap_3__1_3 = QtWidgets.QPushButton(self.tab_2)
        self.KMap_3__1_3.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_3__1_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_3__1_3.setFont(font)
        self.KMap_3__1_3.setObjectName("KMap_3__1_3")
        self.gridLayout_5.addWidget(self.KMap_3__1_3, 7, 2, 1, 1)
        self.line_48 = QtWidgets.QFrame(self.tab_2)
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.gridLayout_5.addWidget(self.line_48, 2, 1, 1, 1)
        self.line_60 = QtWidgets.QFrame(self.tab_2)
        self.line_60.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_60.setObjectName("line_60")
        self.gridLayout_5.addWidget(self.line_60, 1, 3, 1, 1)
        self.line_61 = QtWidgets.QFrame(self.tab_2)
        self.line_61.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_61.setObjectName("line_61")
        self.gridLayout_5.addWidget(self.line_61, 2, 3, 1, 1)
        self.line_62 = QtWidgets.QFrame(self.tab_2)
        self.line_62.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_62.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_62.setObjectName("line_62")
        self.gridLayout_5.addWidget(self.line_62, 3, 3, 1, 1)
        self.line_63 = QtWidgets.QFrame(self.tab_2)
        self.line_63.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_63.setObjectName("line_63")
        self.gridLayout_5.addWidget(self.line_63, 4, 3, 1, 1)
        self.line_66 = QtWidgets.QFrame(self.tab_2)
        self.line_66.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_66.setObjectName("line_66")
        self.gridLayout_5.addWidget(self.line_66, 7, 3, 1, 1)
        self.line_64 = QtWidgets.QFrame(self.tab_2)
        self.line_64.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_64.setObjectName("line_64")
        self.gridLayout_5.addWidget(self.line_64, 5, 3, 1, 1)
        self.line_65 = QtWidgets.QFrame(self.tab_2)
        self.line_65.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_65.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_65.setObjectName("line_65")
        self.gridLayout_5.addWidget(self.line_65, 6, 3, 1, 1)
        self.line_67 = QtWidgets.QFrame(self.tab_2)
        self.line_67.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_67.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_67.setObjectName("line_67")
        self.gridLayout_5.addWidget(self.line_67, 8, 3, 1, 1)
        self.line_47 = QtWidgets.QFrame(self.tab_2)
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.gridLayout_5.addWidget(self.line_47, 1, 1, 1, 1)
        self.line_49 = QtWidgets.QFrame(self.tab_2)
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.gridLayout_5.addWidget(self.line_49, 3, 1, 1, 1)
        self.line_53 = QtWidgets.QFrame(self.tab_2)
        self.line_53.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_53.setObjectName("line_53")
        self.gridLayout_5.addWidget(self.line_53, 8, 1, 1, 1)
        self.KMap_3__0_0 = QtWidgets.QPushButton(self.tab_2)
        self.KMap_3__0_0.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_3__0_0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_3__0_0.setFont(font)
        self.KMap_3__0_0.setObjectName("KMap_3__0_0")
        self.gridLayout_5.addWidget(self.KMap_3__0_0, 1, 2, 1, 1)
        self.line_50 = QtWidgets.QFrame(self.tab_2)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.gridLayout_5.addWidget(self.line_50, 4, 1, 1, 1)
        self.line_52 = QtWidgets.QFrame(self.tab_2)
        self.line_52.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.gridLayout_5.addWidget(self.line_52, 7, 1, 1, 1)
        self.line_51 = QtWidgets.QFrame(self.tab_2)
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.gridLayout_5.addWidget(self.line_51, 6, 1, 1, 1)
        self.line_68 = QtWidgets.QFrame(self.tab_2)
        self.line_68.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_68.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_68.setObjectName("line_68")
        self.gridLayout_5.addWidget(self.line_68, 5, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 4, 4, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 9, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem16 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.result3VarsEditText = QtWidgets.QTextEdit(self.tab_2)
        self.result3VarsEditText.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.result3VarsEditText.setFont(font)
        self.result3VarsEditText.setStyleSheet("color: rgb(43, 88, 132);")
        self.result3VarsEditText.setObjectName("result3VarsEditText")
        self.horizontalLayout_3.addWidget(self.result3VarsEditText)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem17)
        self.buttonSolve3varsMap = QtWidgets.QCommandLinkButton(self.tab_2)
        self.buttonSolve3varsMap.setObjectName("buttonSolve3varsMap")
        self.verticalLayout_4.addWidget(self.buttonSolve3varsMap)
        self.clear3 = QtWidgets.QCommandLinkButton(self.tab_2)
        self.clear3.setObjectName("clear3")
        self.verticalLayout_4.addWidget(self.clear3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_29 = QtWidgets.QFrame(self.tab_3)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout_4.addWidget(self.line_29, 2, 3, 1, 1)
        self.line_32 = QtWidgets.QFrame(self.tab_3)
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.gridLayout_4.addWidget(self.line_32, 2, 6, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.tab_3)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout_4.addWidget(self.line_30, 2, 4, 1, 1)
        self.but_4__0_0 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__0_0.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__0_0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__0_0.setFont(font)
        self.but_4__0_0.setObjectName("but_4__0_0")
        self.gridLayout_4.addWidget(self.but_4__0_0, 3, 3, 1, 1)
        self.line_31 = QtWidgets.QFrame(self.tab_3)
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.gridLayout_4.addWidget(self.line_31, 2, 5, 1, 1)
        self.but_4__1_0 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__1_0.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__1_0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__1_0.setFont(font)
        self.but_4__1_0.setObjectName("but_4__1_0")
        self.gridLayout_4.addWidget(self.but_4__1_0, 4, 3, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.tab_3)
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout_4.addWidget(self.line_35, 5, 2, 1, 1)
        self.line_34 = QtWidgets.QFrame(self.tab_3)
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout_4.addWidget(self.line_34, 4, 2, 1, 1)
        self.line_33 = QtWidgets.QFrame(self.tab_3)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.gridLayout_4.addWidget(self.line_33, 3, 2, 1, 1)
        self.but_4__3_0 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__3_0.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__3_0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__3_0.setFont(font)
        self.but_4__3_0.setObjectName("but_4__3_0")
        self.gridLayout_4.addWidget(self.but_4__3_0, 6, 3, 1, 1)
        self.but_4__3_1 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__3_1.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__3_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__3_1.setFont(font)
        self.but_4__3_1.setObjectName("but_4__3_1")
        self.gridLayout_4.addWidget(self.but_4__3_1, 6, 4, 1, 1)
        self.but_4__2_0 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__2_0.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__2_0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__2_0.setFont(font)
        self.but_4__2_0.setObjectName("but_4__2_0")
        self.gridLayout_4.addWidget(self.but_4__2_0, 5, 3, 1, 1)
        self.but_4__0_1 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__0_1.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__0_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__0_1.setFont(font)
        self.but_4__0_1.setObjectName("but_4__0_1")
        self.gridLayout_4.addWidget(self.but_4__0_1, 3, 4, 1, 1)
        self.but_4__2_1 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__2_1.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__2_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__2_1.setFont(font)
        self.but_4__2_1.setObjectName("but_4__2_1")
        self.gridLayout_4.addWidget(self.but_4__2_1, 5, 4, 1, 1)
        self.but_4__1_1 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__1_1.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__1_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__1_1.setFont(font)
        self.but_4__1_1.setObjectName("but_4__1_1")
        self.gridLayout_4.addWidget(self.but_4__1_1, 4, 4, 1, 1)
        self.but_4__1_2 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__1_2.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__1_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__1_2.setFont(font)
        self.but_4__1_2.setObjectName("but_4__1_2")
        self.gridLayout_4.addWidget(self.but_4__1_2, 4, 5, 1, 1)
        self.but_4__1_3 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__1_3.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__1_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__1_3.setFont(font)
        self.but_4__1_3.setObjectName("but_4__1_3")
        self.gridLayout_4.addWidget(self.but_4__1_3, 4, 6, 1, 1)
        self.but_4__0_2 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__0_2.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__0_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__0_2.setFont(font)
        self.but_4__0_2.setObjectName("but_4__0_2")
        self.gridLayout_4.addWidget(self.but_4__0_2, 3, 5, 1, 1)
        self.but_4__3_2 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__3_2.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__3_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__3_2.setFont(font)
        self.but_4__3_2.setObjectName("but_4__3_2")
        self.gridLayout_4.addWidget(self.but_4__3_2, 6, 5, 1, 1)
        self.but_4__2_2 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__2_2.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__2_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__2_2.setFont(font)
        self.but_4__2_2.setObjectName("but_4__2_2")
        self.gridLayout_4.addWidget(self.but_4__2_2, 5, 5, 1, 1)
        self.but_4__2_3 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__2_3.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__2_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__2_3.setFont(font)
        self.but_4__2_3.setObjectName("but_4__2_3")
        self.gridLayout_4.addWidget(self.but_4__2_3, 5, 6, 1, 1)
        self.line_37 = QtWidgets.QFrame(self.tab_3)
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.gridLayout_4.addWidget(self.line_37, 7, 3, 1, 1)
        self.but_4__3_3 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__3_3.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__3_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__3_3.setFont(font)
        self.but_4__3_3.setObjectName("but_4__3_3")
        self.gridLayout_4.addWidget(self.but_4__3_3, 6, 6, 1, 1)
        self.line_36 = QtWidgets.QFrame(self.tab_3)
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.gridLayout_4.addWidget(self.line_36, 6, 2, 1, 1)
        self.but_4__0_3 = QtWidgets.QPushButton(self.tab_3)
        self.but_4__0_3.setMinimumSize(QtCore.QSize(40, 40))
        self.but_4__0_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_4__0_3.setFont(font)
        self.but_4__0_3.setObjectName("but_4__0_3")
        self.gridLayout_4.addWidget(self.but_4__0_3, 3, 6, 1, 1)
        self.line_44 = QtWidgets.QFrame(self.tab_3)
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.gridLayout_4.addWidget(self.line_44, 6, 7, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem18, 5, 8, 1, 1)
        self.line_43 = QtWidgets.QFrame(self.tab_3)
        self.line_43.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.gridLayout_4.addWidget(self.line_43, 5, 7, 1, 1)
        self.line_38 = QtWidgets.QFrame(self.tab_3)
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.gridLayout_4.addWidget(self.line_38, 7, 4, 1, 1)
        self.line_41 = QtWidgets.QFrame(self.tab_3)
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.gridLayout_4.addWidget(self.line_41, 3, 7, 1, 1)
        self.line_42 = QtWidgets.QFrame(self.tab_3)
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.gridLayout_4.addWidget(self.line_42, 4, 7, 1, 1)
        self.line_40 = QtWidgets.QFrame(self.tab_3)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.gridLayout_4.addWidget(self.line_40, 7, 6, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.tab_3)
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout_4.addWidget(self.line_39, 7, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 4, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 3, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 6, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 1, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 1, 6, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 4, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem20, 0, 3, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem21, 8, 5, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_4)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line_81 = QtWidgets.QFrame(self.tab_3)
        self.line_81.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_81.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_81.setObjectName("line_81")
        self.gridLayout_6.addWidget(self.line_81, 5, 8, 1, 1)
        self.line_82 = QtWidgets.QFrame(self.tab_3)
        self.line_82.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_82.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_82.setObjectName("line_82")
        self.gridLayout_6.addWidget(self.line_82, 6, 8, 1, 1)
        self.line_83 = QtWidgets.QFrame(self.tab_3)
        self.line_83.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_83.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_83.setObjectName("line_83")
        self.gridLayout_6.addWidget(self.line_83, 7, 8, 1, 1)
        self.line_75 = QtWidgets.QFrame(self.tab_3)
        self.line_75.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_75.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_75.setObjectName("line_75")
        self.gridLayout_6.addWidget(self.line_75, 6, 3, 1, 1)
        self.line_78 = QtWidgets.QFrame(self.tab_3)
        self.line_78.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_78.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_78.setObjectName("line_78")
        self.gridLayout_6.addWidget(self.line_78, 2, 8, 1, 1)
        self.line_79 = QtWidgets.QFrame(self.tab_3)
        self.line_79.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_79.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_79.setObjectName("line_79")
        self.gridLayout_6.addWidget(self.line_79, 3, 8, 1, 1)
        self.line_77 = QtWidgets.QFrame(self.tab_3)
        self.line_77.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_77.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_77.setObjectName("line_77")
        self.gridLayout_6.addWidget(self.line_77, 1, 8, 1, 1)
        self.line_76 = QtWidgets.QFrame(self.tab_3)
        self.line_76.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_76.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_76.setObjectName("line_76")
        self.gridLayout_6.addWidget(self.line_76, 7, 3, 1, 1)
        self.line_80 = QtWidgets.QFrame(self.tab_3)
        self.line_80.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_80.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_80.setObjectName("line_80")
        self.gridLayout_6.addWidget(self.line_80, 4, 8, 1, 1)
        self.line_45 = QtWidgets.QFrame(self.tab_3)
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.gridLayout_6.addWidget(self.line_45, 2, 1, 1, 1)
        self.line_54 = QtWidgets.QFrame(self.tab_3)
        self.line_54.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.gridLayout_6.addWidget(self.line_54, 3, 1, 1, 1)
        self.line_55 = QtWidgets.QFrame(self.tab_3)
        self.line_55.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.gridLayout_6.addWidget(self.line_55, 4, 1, 1, 1)
        self.line_57 = QtWidgets.QFrame(self.tab_3)
        self.line_57.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_57.setObjectName("line_57")
        self.gridLayout_6.addWidget(self.line_57, 6, 1, 1, 1)
        self.line_56 = QtWidgets.QFrame(self.tab_3)
        self.line_56.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.gridLayout_6.addWidget(self.line_56, 5, 1, 1, 1)
        self.line_58 = QtWidgets.QFrame(self.tab_3)
        self.line_58.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_58.setObjectName("line_58")
        self.gridLayout_6.addWidget(self.line_58, 7, 1, 1, 1)
        self.line_69 = QtWidgets.QFrame(self.tab_3)
        self.line_69.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_69.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_69.setObjectName("line_69")
        self.gridLayout_6.addWidget(self.line_69, 9, 1, 1, 1)
        self.line_59 = QtWidgets.QFrame(self.tab_3)
        self.line_59.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_59.setObjectName("line_59")
        self.gridLayout_6.addWidget(self.line_59, 8, 1, 1, 1)
        self.line_71 = QtWidgets.QFrame(self.tab_3)
        self.line_71.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_71.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_71.setObjectName("line_71")
        self.gridLayout_6.addWidget(self.line_71, 2, 3, 1, 1)
        self.line_70 = QtWidgets.QFrame(self.tab_3)
        self.line_70.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_70.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_70.setObjectName("line_70")
        self.gridLayout_6.addWidget(self.line_70, 1, 3, 1, 1)
        self.line_73 = QtWidgets.QFrame(self.tab_3)
        self.line_73.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_73.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_73.setObjectName("line_73")
        self.gridLayout_6.addWidget(self.line_73, 4, 3, 1, 1)
        self.line_74 = QtWidgets.QFrame(self.tab_3)
        self.line_74.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_74.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_74.setObjectName("line_74")
        self.gridLayout_6.addWidget(self.line_74, 5, 3, 1, 1)
        self.line_72 = QtWidgets.QFrame(self.tab_3)
        self.line_72.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_72.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_72.setObjectName("line_72")
        self.gridLayout_6.addWidget(self.line_72, 3, 3, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.tab_3)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_6.addWidget(self.line_14, 1, 1, 1, 1)
        self.KMap_4__0_0 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__0_0.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__0_0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__0_0.setFont(font)
        self.KMap_4__0_0.setObjectName("KMap_4__0_0")
        self.gridLayout_6.addWidget(self.KMap_4__0_0, 1, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 4, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 3, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 5, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 7, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 6, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 8, 0, 1, 1)
        self.KMap_4__0_1 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__0_1.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__0_1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__0_1.setFont(font)
        self.KMap_4__0_1.setObjectName("KMap_4__0_1")
        self.gridLayout_6.addWidget(self.KMap_4__0_1, 2, 2, 1, 1)
        self.KMap_4__0_3 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__0_3.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__0_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__0_3.setFont(font)
        self.KMap_4__0_3.setObjectName("KMap_4__0_3")
        self.gridLayout_6.addWidget(self.KMap_4__0_3, 3, 2, 1, 1)
        self.KMap_4__0_2 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__0_2.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__0_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__0_2.setFont(font)
        self.KMap_4__0_2.setObjectName("KMap_4__0_2")
        self.gridLayout_6.addWidget(self.KMap_4__0_2, 4, 2, 1, 1)
        self.KMap_4__1_3 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__1_3.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__1_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__1_3.setFont(font)
        self.KMap_4__1_3.setObjectName("KMap_4__1_3")
        self.gridLayout_6.addWidget(self.KMap_4__1_3, 7, 2, 1, 1)
        self.KMap_4__1_0 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__1_0.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__1_0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__1_0.setFont(font)
        self.KMap_4__1_0.setObjectName("KMap_4__1_0")
        self.gridLayout_6.addWidget(self.KMap_4__1_0, 5, 2, 1, 1)
        self.KMap_4__1_1 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__1_1.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__1_1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__1_1.setFont(font)
        self.KMap_4__1_1.setObjectName("KMap_4__1_1")
        self.gridLayout_6.addWidget(self.KMap_4__1_1, 6, 2, 1, 1)
        self.KMap_4__1_2 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__1_2.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__1_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__1_2.setFont(font)
        self.KMap_4__1_2.setObjectName("KMap_4__1_2")
        self.gridLayout_6.addWidget(self.KMap_4__1_2, 8, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 9, 0, 1, 1)
        self.KMap_4__3_0 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__3_0.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__3_0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__3_0.setFont(font)
        self.KMap_4__3_0.setObjectName("KMap_4__3_0")
        self.gridLayout_6.addWidget(self.KMap_4__3_0, 9, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 4, 5, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 2, 5, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 1, 5, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_45.setObjectName("label_45")
        self.gridLayout_6.addWidget(self.label_45, 3, 5, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 7, 5, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_48.setObjectName("label_48")
        self.gridLayout_6.addWidget(self.label_48, 6, 5, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_47.setObjectName("label_47")
        self.gridLayout_6.addWidget(self.label_47, 5, 5, 1, 1)
        self.KMap_4__3_1 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__3_1.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__3_1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__3_1.setFont(font)
        self.KMap_4__3_1.setObjectName("KMap_4__3_1")
        self.gridLayout_6.addWidget(self.KMap_4__3_1, 1, 7, 1, 1)
        self.KMap_4__3_2 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__3_2.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__3_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__3_2.setFont(font)
        self.KMap_4__3_2.setObjectName("KMap_4__3_2")
        self.gridLayout_6.addWidget(self.KMap_4__3_2, 3, 7, 1, 1)
        self.KMap_4__3_3 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__3_3.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__3_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__3_3.setFont(font)
        self.KMap_4__3_3.setObjectName("KMap_4__3_3")
        self.gridLayout_6.addWidget(self.KMap_4__3_3, 2, 7, 1, 1)
        self.KMap_4__2_1 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__2_1.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__2_1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__2_1.setFont(font)
        self.KMap_4__2_1.setObjectName("KMap_4__2_1")
        self.gridLayout_6.addWidget(self.KMap_4__2_1, 5, 7, 1, 1)
        self.KMap_4__2_3 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__2_3.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__2_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__2_3.setFont(font)
        self.KMap_4__2_3.setObjectName("KMap_4__2_3")
        self.gridLayout_6.addWidget(self.KMap_4__2_3, 6, 7, 1, 1)
        self.KMap_4__2_0 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__2_0.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__2_0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__2_0.setFont(font)
        self.KMap_4__2_0.setObjectName("KMap_4__2_0")
        self.gridLayout_6.addWidget(self.KMap_4__2_0, 4, 7, 1, 1)
        self.KMap_4__2_2 = QtWidgets.QPushButton(self.tab_3)
        self.KMap_4__2_2.setMinimumSize(QtCore.QSize(0, 30))
        self.KMap_4__2_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KMap_4__2_2.setFont(font)
        self.KMap_4__2_2.setObjectName("KMap_4__2_2")
        self.gridLayout_6.addWidget(self.KMap_4__2_2, 7, 7, 1, 1)
        self.line_85 = QtWidgets.QFrame(self.tab_3)
        self.line_85.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_85.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_85.setObjectName("line_85")
        self.gridLayout_6.addWidget(self.line_85, 2, 6, 1, 1)
        self.line_84 = QtWidgets.QFrame(self.tab_3)
        self.line_84.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_84.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_84.setObjectName("line_84")
        self.gridLayout_6.addWidget(self.line_84, 1, 6, 1, 1)
        self.line_88 = QtWidgets.QFrame(self.tab_3)
        self.line_88.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_88.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_88.setObjectName("line_88")
        self.gridLayout_6.addWidget(self.line_88, 5, 6, 1, 1)
        self.line_89 = QtWidgets.QFrame(self.tab_3)
        self.line_89.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_89.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_89.setObjectName("line_89")
        self.gridLayout_6.addWidget(self.line_89, 6, 6, 1, 1)
        self.line_90 = QtWidgets.QFrame(self.tab_3)
        self.line_90.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_90.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_90.setObjectName("line_90")
        self.gridLayout_6.addWidget(self.line_90, 7, 6, 1, 1)
        self.line_86 = QtWidgets.QFrame(self.tab_3)
        self.line_86.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_86.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_86.setObjectName("line_86")
        self.gridLayout_6.addWidget(self.line_86, 3, 6, 1, 1)
        self.line_87 = QtWidgets.QFrame(self.tab_3)
        self.line_87.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_87.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_87.setObjectName("line_87")
        self.gridLayout_6.addWidget(self.line_87, 4, 6, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem23, 6, 9, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem24, 0, 7, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem25, 10, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setMinimumSize(QtCore.QSize(30, 0))
        self.widget.setMaximumSize(QtCore.QSize(30, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_6.addWidget(self.widget, 3, 4, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem26)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.result4VarsEditText = QtWidgets.QTextEdit(self.tab_3)
        self.result4VarsEditText.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.result4VarsEditText.setFont(font)
        self.result4VarsEditText.setStyleSheet("color: rgb(43, 88, 132);")
        self.result4VarsEditText.setObjectName("result4VarsEditText")
        self.horizontalLayout_4.addWidget(self.result4VarsEditText)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem27)
        self.buttonSolve4varsMap = QtWidgets.QCommandLinkButton(self.tab_3)
        self.buttonSolve4varsMap.setObjectName("buttonSolve4varsMap")
        self.verticalLayout_6.addWidget(self.buttonSolve4varsMap)
        self.clear4 = QtWidgets.QCommandLinkButton(self.tab_3)
        self.clear4.setObjectName("clear4")
        self.verticalLayout_6.addWidget(self.clear4)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_50 = QtWidgets.QLabel(self.tab_4)
        self.label_50.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_3.addWidget(self.label_50)
        self.line_91 = QtWidgets.QFrame(self.tab_4)
        self.line_91.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_91.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_91.setObjectName("line_91")
        self.verticalLayout_3.addWidget(self.line_91)
        self.label_54 = QtWidgets.QLabel(self.tab_4)
        self.label_54.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_3.addWidget(self.label_54)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_52 = QtWidgets.QLabel(self.tab_4)
        self.label_52.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: #FF3D00;")
        self.label_52.setObjectName("label_52")
        self.gridLayout_7.addWidget(self.label_52, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem28, 1, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_4)
        self.label_53.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color: #FF4081;")
        self.label_53.setObjectName("label_53")
        self.gridLayout_7.addWidget(self.label_53, 0, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_4)
        self.label_51.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: #76FF03;")
        self.label_51.setObjectName("label_51")
        self.gridLayout_7.addWidget(self.label_51, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_55.setObjectName("label_55")
        self.gridLayout_7.addWidget(self.label_55, 0, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 1, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_57.setObjectName("label_57")
        self.gridLayout_7.addWidget(self.label_57, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem29)
        self.label_58 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("color: rgb(70, 141, 212);")
        self.label_58.setObjectName("label_58")
        self.verticalLayout_3.addWidget(self.label_58)
        self.line_92 = QtWidgets.QFrame(self.tab_4)
        self.line_92.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_92.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_92.setObjectName("line_92")
        self.verticalLayout_3.addWidget(self.line_92)
        self.howToUseKMapSolverButton = QtWidgets.QCommandLinkButton(self.tab_4)
        self.howToUseKMapSolverButton.setObjectName("howToUseKMapSolverButton")
        self.verticalLayout_3.addWidget(self.howToUseKMapSolverButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        KMapSolvers.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(KMapSolvers)
        self.statusbar.setObjectName("statusbar")
        KMapSolvers.setStatusBar(self.statusbar)

        self.retranslateUi(KMapSolvers)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(KMapSolvers)

    def retranslateUi(self, KMapSolvers):
        _translate = QtCore.QCoreApplication.translate
        KMapSolvers.setWindowTitle(_translate("KMapSolvers", "Karnaugh Maps Solver"))
        self.label_3.setText(_translate("KMapSolvers", "A(0)"))
        self.but_2__1_0.setText(_translate("KMapSolvers", "0"))
        self.but_2__0_1.setText(_translate("KMapSolvers", "0"))
        self.but_2__0_0.setText(_translate("KMapSolvers", "0"))
        self.label.setText(_translate("KMapSolvers", "B(0)"))
        self.label_2.setText(_translate("KMapSolvers", "B(1)"))
        self.label_4.setText(_translate("KMapSolvers", "A(1)"))
        self.but_2__1_1.setText(_translate("KMapSolvers", "0"))
        self.label_7.setText(_translate("KMapSolvers", "0"))
        self.label_8.setText(_translate("KMapSolvers", "1"))
        self.label_9.setText(_translate("KMapSolvers", "2"))
        self.label_26.setText(_translate("KMapSolvers", "3"))
        self.KMap_2__0_1.setText(_translate("KMapSolvers", "0"))
        self.KMap_2__0_0.setText(_translate("KMapSolvers", "0"))
        self.KMap_2__1_0.setText(_translate("KMapSolvers", "0"))
        self.KMap_2__1_1.setText(_translate("KMapSolvers", "0"))
        self.label_5.setText(_translate("KMapSolvers", "Result Function: "))
        self.buttonSolve2varsMap.setText(_translate("KMapSolvers", "Solve Map"))
        self.clear2.setText(_translate("KMapSolvers", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("KMapSolvers", "2 Variables"))
        self.label_15.setText(_translate("KMapSolvers", "BC(1,0)"))
        self.but_3__0_0.setText(_translate("KMapSolvers", "0"))
        self.but_3__1_3.setText(_translate("KMapSolvers", "0"))
        self.but_3__0_1.setText(_translate("KMapSolvers", "0"))
        self.but_3__1_0.setText(_translate("KMapSolvers", "0"))
        self.but_3__0_3.setText(_translate("KMapSolvers", "0"))
        self.label_14.setText(_translate("KMapSolvers", "BC(1,1)"))
        self.but_3__0_2.setText(_translate("KMapSolvers", "0"))
        self.but_3__1_1.setText(_translate("KMapSolvers", "0"))
        self.but_3__1_2.setText(_translate("KMapSolvers", "0"))
        self.label_10.setText(_translate("KMapSolvers", "A(0)"))
        self.label_13.setText(_translate("KMapSolvers", "BC(0,1)"))
        self.label_11.setText(_translate("KMapSolvers", "A(1)"))
        self.label_12.setText(_translate("KMapSolvers", "BC(0,0)"))
        self.label_29.setText(_translate("KMapSolvers", "3"))
        self.label_30.setText(_translate("KMapSolvers", "4"))
        self.label_33.setText(_translate("KMapSolvers", "7"))
        self.label_32.setText(_translate("KMapSolvers", "6"))
        self.label_31.setText(_translate("KMapSolvers", "5"))
        self.label_6.setText(_translate("KMapSolvers", "0"))
        self.label_27.setText(_translate("KMapSolvers", "1"))
        self.label_28.setText(_translate("KMapSolvers", "2"))
        self.KMap_3__0_3.setText(_translate("KMapSolvers", "0"))
        self.KMap_3__0_1.setText(_translate("KMapSolvers", "0"))
        self.KMap_3__0_2.setText(_translate("KMapSolvers", "0"))
        self.KMap_3__1_0.setText(_translate("KMapSolvers", "0"))
        self.KMap_3__1_1.setText(_translate("KMapSolvers", "0"))
        self.KMap_3__1_2.setText(_translate("KMapSolvers", "0"))
        self.KMap_3__1_3.setText(_translate("KMapSolvers", "0"))
        self.KMap_3__0_0.setText(_translate("KMapSolvers", "0"))
        self.label_16.setText(_translate("KMapSolvers", "Result function: "))
        self.buttonSolve3varsMap.setText(_translate("KMapSolvers", "Solve Map"))
        self.clear3.setText(_translate("KMapSolvers", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("KMapSolvers", "3 Variables"))
        self.but_4__0_0.setText(_translate("KMapSolvers", "0"))
        self.but_4__1_0.setText(_translate("KMapSolvers", "0"))
        self.but_4__3_0.setText(_translate("KMapSolvers", "0"))
        self.but_4__3_1.setText(_translate("KMapSolvers", "0"))
        self.but_4__2_0.setText(_translate("KMapSolvers", "0"))
        self.but_4__0_1.setText(_translate("KMapSolvers", "0"))
        self.but_4__2_1.setText(_translate("KMapSolvers", "0"))
        self.but_4__1_1.setText(_translate("KMapSolvers", "0"))
        self.but_4__1_2.setText(_translate("KMapSolvers", "0"))
        self.but_4__1_3.setText(_translate("KMapSolvers", "0"))
        self.but_4__0_2.setText(_translate("KMapSolvers", "0"))
        self.but_4__3_2.setText(_translate("KMapSolvers", "0"))
        self.but_4__2_2.setText(_translate("KMapSolvers", "0"))
        self.but_4__2_3.setText(_translate("KMapSolvers", "0"))
        self.but_4__3_3.setText(_translate("KMapSolvers", "0"))
        self.but_4__0_3.setText(_translate("KMapSolvers", "0"))
        self.label_19.setText(_translate("KMapSolvers", "AB(0,1)"))
        self.label_20.setText(_translate("KMapSolvers", "AB(1,1)"))
        self.label_18.setText(_translate("KMapSolvers", "AB(0,0)"))
        self.label_21.setText(_translate("KMapSolvers", "AB(1,0)"))
        self.label_24.setText(_translate("KMapSolvers", "CD(1,1)"))
        self.label_22.setText(_translate("KMapSolvers", "CD(0,0)"))
        self.label_25.setText(_translate("KMapSolvers", "CD(1,0)"))
        self.label_23.setText(_translate("KMapSolvers", "CD(0,1)"))
        self.KMap_4__0_0.setText(_translate("KMapSolvers", "0"))
        self.label_34.setText(_translate("KMapSolvers", "0"))
        self.label_37.setText(_translate("KMapSolvers", "3"))
        self.label_35.setText(_translate("KMapSolvers", "1"))
        self.label_36.setText(_translate("KMapSolvers", "2"))
        self.label_38.setText(_translate("KMapSolvers", "4"))
        self.label_40.setText(_translate("KMapSolvers", "6"))
        self.label_39.setText(_translate("KMapSolvers", "5"))
        self.label_41.setText(_translate("KMapSolvers", "7"))
        self.KMap_4__0_1.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__0_3.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__0_2.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__1_3.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__1_0.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__1_1.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__1_2.setText(_translate("KMapSolvers", "0"))
        self.label_42.setText(_translate("KMapSolvers", "8"))
        self.KMap_4__3_0.setText(_translate("KMapSolvers", "0"))
        self.label_46.setText(_translate("KMapSolvers", "12"))
        self.label_44.setText(_translate("KMapSolvers", "10"))
        self.label_43.setText(_translate("KMapSolvers", "9"))
        self.label_45.setText(_translate("KMapSolvers", "11"))
        self.label_49.setText(_translate("KMapSolvers", "15"))
        self.label_48.setText(_translate("KMapSolvers", "14"))
        self.label_47.setText(_translate("KMapSolvers", "13"))
        self.KMap_4__3_1.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__3_2.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__3_3.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__2_1.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__2_3.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__2_0.setText(_translate("KMapSolvers", "0"))
        self.KMap_4__2_2.setText(_translate("KMapSolvers", "0"))
        self.label_17.setText(_translate("KMapSolvers", "Result Function: "))
        self.buttonSolve4varsMap.setText(_translate("KMapSolvers", "Solve Map"))
        self.clear4.setText(_translate("KMapSolvers", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("KMapSolvers", "4 Variables"))
        self.label_50.setText(_translate("KMapSolvers", "Help"))
        self.label_54.setText(_translate("KMapSolvers", "These colors represent same grouped minterms."))
        self.label_52.setText(_translate("KMapSolvers", "O"))
        self.label_53.setText(_translate("KMapSolvers", "O"))
        self.label_51.setText(_translate("KMapSolvers", "O"))
        self.label_55.setText(_translate("KMapSolvers", "The minterm is used by two groups."))
        self.label_56.setText(_translate("KMapSolvers", "The minterm is used by three groups."))
        self.label_57.setText(_translate("KMapSolvers", "The minterm is used by four groups."))
        self.label_58.setText(_translate("KMapSolvers", "Need More Help?"))
        self.howToUseKMapSolverButton.setText(_translate("KMapSolvers", "How to use Karnaugh Maps Solver!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("KMapSolvers", "Help"))

