# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseConverter.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BaseConverter(object):
    def setupUi(self, BaseConverter):
        BaseConverter.setObjectName("BaseConverter")
        BaseConverter.resize(544, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BaseConverter.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BaseConverter)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(55, 115, 171);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.primaryNumberText = QtWidgets.QTextEdit(self.centralwidget)
        self.primaryNumberText.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.primaryNumberText.setFont(font)
        self.primaryNumberText.setStyleSheet("color: rgb(38, 78, 117);")
        self.primaryNumberText.setObjectName("primaryNumberText")
        self.verticalLayout.addWidget(self.primaryNumberText)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(55, 115, 171);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.baseFromN1 = QtWidgets.QSpinBox(self.centralwidget)
        self.baseFromN1.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.baseFromN1.setFont(font)
        self.baseFromN1.setStyleSheet("color: rgb(38, 78, 117);")
        self.baseFromN1.setMinimum(2)
        self.baseFromN1.setMaximum(36)
        self.baseFromN1.setObjectName("baseFromN1")
        self.horizontalLayout_3.addWidget(self.baseFromN1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(55, 115, 171);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.secondaryNumberText = QtWidgets.QTextEdit(self.centralwidget)
        self.secondaryNumberText.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.secondaryNumberText.setFont(font)
        self.secondaryNumberText.setStyleSheet("color: rgb(38, 78, 117);")
        self.secondaryNumberText.setObjectName("secondaryNumberText")
        self.verticalLayout_2.addWidget(self.secondaryNumberText)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(55, 115, 171);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.baseToN2 = QtWidgets.QSpinBox(self.centralwidget)
        self.baseToN2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.baseToN2.setFont(font)
        self.baseToN2.setStyleSheet("color: rgb(38, 78, 117);")
        self.baseToN2.setMinimum(2)
        self.baseToN2.setMaximum(36)
        self.baseToN2.setObjectName("baseToN2")
        self.horizontalLayout_6.addWidget(self.baseToN2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        BaseConverter.setCentralWidget(self.centralwidget)

        self.retranslateUi(BaseConverter)
        QtCore.QMetaObject.connectSlotsByName(BaseConverter)

    def retranslateUi(self, BaseConverter):
        _translate = QtCore.QCoreApplication.translate
        BaseConverter.setWindowTitle(_translate("BaseConverter", "Base Converter"))
        self.label.setText(_translate("BaseConverter", "Number:"))
        self.label_2.setText(_translate("BaseConverter", "Base From:"))
        self.label_4.setText(_translate("BaseConverter", "Number:"))
        self.label_6.setText(_translate("BaseConverter", "Base To:"))


