# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuineMcCluskeySolverGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QuineMcCluskeyGui(object):
    def setupUi(self, QuineMcCluskeyGui):
        QuineMcCluskeyGui.setObjectName("QuineMcCluskeyGui")
        QuineMcCluskeyGui.resize(781, 510)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QuineMcCluskeyGui.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(QuineMcCluskeyGui)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(60, 121, 182);")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.editMinterm = QtWidgets.QLineEdit(self.centralwidget)
        self.editMinterm.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.editMinterm.setFont(font)
        self.editMinterm.setStyleSheet("color: rgb(43, 88, 132);")
        self.editMinterm.setObjectName("editMinterm")
        self.horizontalLayout_3.addWidget(self.editMinterm)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(60, 121, 182);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.editDCMinterm = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.editDCMinterm.setFont(font)
        self.editDCMinterm.setStyleSheet("color: rgb(43, 88, 132);")
        self.editDCMinterm.setObjectName("editDCMinterm")
        self.horizontalLayout_4.addWidget(self.editDCMinterm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addMintermButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.addMintermButton.setObjectName("addMintermButton")
        self.horizontalLayout_5.addWidget(self.addMintermButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minterms = QtWidgets.QListWidget(self.centralwidget)
        self.minterms.setMaximumSize(QtCore.QSize(150, 16777215))
        self.minterms.setStyleSheet("color: rgb(43, 88, 132);")
        self.minterms.setObjectName("minterms")
        self.horizontalLayout.addWidget(self.minterms)
        self.resultTable = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.resultTable.setFont(font)
        self.resultTable.setStyleSheet("color: rgb(43, 88, 132);")
        self.resultTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.resultTable.setShowGrid(True)
        self.resultTable.setGridStyle(QtCore.Qt.DashLine)
        self.resultTable.setCornerButtonEnabled(False)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(3)
        self.resultTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(2, item)
        self.resultTable.horizontalHeader().setDefaultSectionSize(122)
        self.horizontalLayout.addWidget(self.resultTable)
        self.finalTable = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.finalTable.setFont(font)
        self.finalTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.finalTable.setStyleSheet("color: rgb(43, 88, 132);")
        self.finalTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.finalTable.setObjectName("finalTable")
        self.finalTable.setColumnCount(0)
        self.finalTable.setRowCount(0)
        self.horizontalLayout.addWidget(self.finalTable)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(60, 121, 182);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.editResultFunction = QtWidgets.QLineEdit(self.centralwidget)
        self.editResultFunction.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.editResultFunction.setFont(font)
        self.editResultFunction.setStyleSheet("color: rgb(43, 88, 132);")
        self.editResultFunction.setText("")
        self.editResultFunction.setObjectName("editResultFunction")
        self.horizontalLayout_2.addWidget(self.editResultFunction)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.solveButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.solveButton.setObjectName("solveButton")
        self.verticalLayout_2.addWidget(self.solveButton)
        self.ClearButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.ClearButton.setObjectName("ClearButton")
        self.verticalLayout_2.addWidget(self.ClearButton)
        QuineMcCluskeyGui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(QuineMcCluskeyGui)
        self.statusbar.setObjectName("statusbar")
        QuineMcCluskeyGui.setStatusBar(self.statusbar)

        self.retranslateUi(QuineMcCluskeyGui)
        QtCore.QMetaObject.connectSlotsByName(QuineMcCluskeyGui)

    def retranslateUi(self, QuineMcCluskeyGui):
        _translate = QtCore.QCoreApplication.translate
        QuineMcCluskeyGui.setWindowTitle(_translate("QuineMcCluskeyGui", "Quine McCluskey Solver"))
        self.label.setText(_translate("QuineMcCluskeyGui", "Give a minterm: "))
        self.label_3.setText(_translate("QuineMcCluskeyGui", "Give a DC minterm:"))
        self.addMintermButton.setText(_translate("QuineMcCluskeyGui", "Add Minterm"))
        item = self.resultTable.horizontalHeaderItem(0)
        item.setText(_translate("QuineMcCluskeyGui", "Minterms(Binary)"))
        item = self.resultTable.horizontalHeaderItem(1)
        item.setText(_translate("QuineMcCluskeyGui", "Result Table"))
        item = self.resultTable.horizontalHeaderItem(2)
        item.setText(_translate("QuineMcCluskeyGui", "Result Table (Letters)"))
        self.label_2.setText(_translate("QuineMcCluskeyGui", "Result Function: "))
        self.solveButton.setText(_translate("QuineMcCluskeyGui", "Solve"))
        self.ClearButton.setText(_translate("QuineMcCluskeyGui", "Clear"))

